routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\RatingController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\KatalogController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashbordController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\kategoriController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\KeranjangController;
use App\Http\Controllers\BackgroundController;
use App\Http\Controllers\KonfirmasiController;
use App\Http\Controllers\PengirimanController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\SpesifikasiProdukController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);
Route::get('/detail/{id}', [BlogController::class, 'index']);
Route::get('/kategori/{id}', [CatalogController::class, 'index']);


Route::post('/konfirmasi', [CheckoutController::class, 'konfirmasi'])->middleware('auth');

Route::post('/pembayaran', [PengirimanController::class, 'pembayaran'])->middleware('auth');
Route::get('/pembayaran/{id}', [PengirimanController::class, 'detailPembayaran'])->middleware('auth');
Route::post('/pembayaranrating/{id}', [RatingController::class, 'ratingPembayaran'])->middleware('auth');

Route::get('/pesanan', [PengirimanController::class, 'pesananSelesai'])->middleware('auth');

Route::post('/pembayaran/{id}/uplod-bukti', [PengirimanController::class, 'update'])->middleware('auth');
Route::get('/checkout', [CheckoutController::class, 'index'])->middleware('auth');
Route::get('/kota/{provinsi_id}', [KotaController::class, 'get']);
Route::post('/checkout/get-ongkir', [CheckoutController::class, 'getOngkir']);
Route::post('/user/selesai/{id}/updatestatusselesai', [PengirimanController::class, 'updatestatususer']);



//menu profile
Route::get('/profile', [ProfileController::class, 'index'])->middleware('auth');
Route::post('/profile/profilesaya', [ProfileController::class, 'profilesaya'])->middleware('auth');

//menu login
Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::get('/logout', [LoginController::class, 'logout']);


//register
Route::get('/register', [RegisterController::class, 'index'])->name('register')->middleware('guest');
Route::post('/register', [RegisterController::class, 'store']);

//front

Route::resource('/dashbord/index', DashbordController::class);
//Dashbord admin
Route::resource('/dashbord/kategori', KategoriController::class);
Route::resource('/dashbord/produk', ProdukController::class);
Route::resource('/dashbord/spesifikasiproduk', SpesifikasiProdukController::class);
Route::resource('/dashbord/kota', KotaController::class);
Route::resource('/dashbord/provinsi', ProvinsiController::class);
Route::resource('/dashbord/background', BackgroundController::class);   
Route::resource('/dashbord/bank', BankController::class);
Route::resource('/dashbord/size', SizeController::class);



//pesanan dahbord
Route::get('/dashbord/pesananbaru', [PengirimanController::class, 'pesananbaru']);
Route::get('/dashbord/pesananbaru/{id}/detail', [PengirimanController::class, 'detailPesanan']);
Route::post('/dashbord/pesananbaru/{id}/updatestatus', [PengirimanController::class, 'updatestatuspesananbaru']);

//proses pesanan
Route::get('/dashbord/sedangdiproses', [PengirimanController::class, 'sedangdiproses']);
Route::get('/dashbord/sedangdiproses/{id}/detail', [PengirimanController::class, 'detailProses']);
Route::post('/dashbord/sedangdiproses/{id}/updatestatus', [PengirimanController::class, 'updatestatussedangdiproses']);

//pengiriman pesanan
Route::get('/dashbord/dalampengiriman', [PengirimanController::class, 'dalampengiriman']);
Route::get('/dashbord/dalampengiriman/{id}/detail', [PengirimanController::class, 'detailPengiriman']);
Route::post('/dashbord/dalampengiriman/{id}/updatestatus', [PengirimanController::class, 'updatestatusdalampengiriman']);
 
//pesanan selesai
Route::get('/dashbord/telahselesai', [PengirimanController::class, 'telahselesai']);
Route::get('/dashbord/telahselesai/{id}/detail', [PengirimanController::class, 'detailSelesai']);

//PDF
Route::get('/dashbord/telahselesai/detail-pdf/{id}', [PdfController::class, 'pdfselesai']);
Route::get('/dashbord/pdfreport/detail-pdf', [PdfController::class, 'reportpdf']);
Route::get('/dashbord/pesananbaru/detail-pdf/{id}', [PdfController::class, 'pdfpesananBaru']);
Route::get('/dashbord/dalampengiriman/detail-pdf/{id}', [PdfController::class, 'pdfdalamPengiriman']);
Route::get('/dashbord/sedangdiproses/detail-pdf/{id}', [PdfController::class, 'pdfsedangDiproses']);

//keranjang
Route::get('/keranjang', [KeranjangController::class, 'index'])->middleware('auth');
Route::post('/keranjang/create', [KeranjangController::class, 'store'])->name('keranjang.store')->middleware('auth');
Route::post('/keranjang/{id}', [KeranjangController::class, 'update'])->middleware('auth');
Route::delete('/keranjang/{id}', [KeranjangController::class, 'delete'])->middleware('auth');

app/Models/Background.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Background extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Http/Controllers/BackgroundController.php
<?php

namespace App\Http\Controllers;

use App\Models\Background;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BackgroundController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $background = Background::all();
        $keyword = $request->keyword;
        return view('dashbord.Background.index', compact( 
            'background'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tambah = Background::all();
        return view('dashbord.Background.create', compact(
            'tambah'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'gambar' => 'required|file|max:1024'
        ]);
        $background = $request->all();
        if($request->file('gambar')){
            $background['gambar'] = $request->file('gambar')->store('Background-image');
        }
        Background::create($background);
        return redirect('dashbord/background')->with('successcreate', 'Create Successfull!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Background  $background
     * @return \Illuminate\Http\Response
     */
    public function show(Background $background)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Background  $background
     * @return \Illuminate\Http\Response
     */
    public function edit(Background $background)
    {

        return view('dashbord.Background.edit', compact(
            'background',
            
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Background  $background
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Background $background)
    {
        $validatedData = $request->validate([
            'gambar' => 'required|file|max:1024'
        ]);
        if($request->file('gambar')){
            $validatedData['gambar'] = $request->file('gambar')->store('Background-image', 'public');
        }
        $tambah = Background::find($background->id);
        $tambah->update($validatedData);
        return redirect('dashbord/background')->with('successupdate', 'Update Successfull!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Background  $background
     * @return \Illuminate\Http\Response
     */
    public function destroy(Background $background)
    {
        $background->delete();
        return redirect('dashbord/background')->with('successdelete', 'Delete Successfull!');
    }
   
}

app/Http/Controllers/DashbordController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Produk;
use App\Models\Rating;
use App\Models\pesanan;
use App\Models\Setting;
use App\Models\Checkout;
use App\Models\Pembayaran;
use App\Models\Pengiriman;
use Illuminate\Http\Request;

class DashbordController extends Controller
{
    public function index()
    {
        $user = User::where('is_admin','0')->paginate(5);
        $produk = Produk::get();
        $totalPendapatan = Checkout::where('status', 'Telah Selesai')->sum('total_harga');
        $totalOngkir = Pengiriman::whereHas('checkout', function ($q) {
            $q->where('status', 'Telah Selesai');
        })->sum('harga_ongkir');
        $totalPendapatan = $totalPendapatan - $totalOngkir;

        $totalPenjualan = pesanan::sum('kuantitas');
        $checkout = Checkout::get();
        $ratingKomen = Rating::where('produk_id')->get();


        return view('dashbord.index', compact(
            'produk',
            'totalPendapatan',
            'totalOngkir',
            'user',
            'checkout',
            'ratingKomen'
        ));
    }
}

resources/views/dashbord/background/create.blade.php
@extends('dashbord.layouts.main')

@section('container')
<div class="container">
    <div class="card card-custom card-create">
        <div class="card-body">
            <form action="{{ url('dashbord/background') }}" method="POST" enctype="multipart/form-data">
                @csrf
                  <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-4 mb-3">
                          <label class="required form-label">Image</label> 
                          <input type="file" accept="jpg, png, jpeg" name="gambar" class="form-control">
                        </div>
                        <div class="kt-form__actions mt-5">
                          <button type="submit" class="btn btn-primary btn-sm mb-2 me-2">
                            <i class="las la-save fs-2 me-2"></i> SAVE</button> 
                          <a href="/dashbord/background/"  type="button" class="btn btn-danger btn-sm mb-2 me-2">
                            <i class="las la-ban fs-2 me-2"> </i> CANCEL
                          </a>
                    </div>
                  </div>
            </form>
@endsection

resources/views/dashbord/background/edit.blade.php
@extends('dashbord.layouts.main')


@section('container')
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <div class="toolbar" id="kt_toolbar">
            <div id="kt_toolbar_container" class="container-fluid d-flex flex-stack">
                <div data-kt-swapper="true" data-kt-swapper-mode="prepend"
                    data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}"
                    class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
                    <h1 class="d-flex align-items-center text-dark fw-bolder fs-3 my-1">Background</h1>
                    <span class="h-20px border-gray-300 border-start mx-4"></span>
                </div>

                <div class="d-flex align-items-center gap-2 gap-lg-3">


                </div>

            </div>

        </div>
        <div class="card card-custom card-create">
            <div class="card-body">
                <form action="{{ url('dashbord/background/' . $background->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="_method" value="PATCH">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="mb-4">
                                <label class="required form-label">Gambar</label>
                                <input type="file" accept="jpg, png, jpeg" name="gambar"  class="form-control" value="{{ $background->gambar }}">
                            </div>
                        </div>
                        <div class="kt-form__actions mt-5">
                            <button type="submit" class="btn btn-primary btn-sm mb-2 me-2">
                                <i class="las la-save fs-2 me-2"></i> SAVE</button>
                            <a href="/dashbord/kategori" type="button" class="btn btn-danger btn-sm mb-2 me-2">
                                <i class="las la-ban fs-2 me-2"> </i> CANCEL
                            </a>
                        </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/dashbord/background/index.blade.php
@extends('dashbord.layouts.main')

@section('container')
    <div id="kt_app_content" class="app-content flex-column-fluid">
        <!--begin::Content container-->
        <div id="kt_app_content_container" class="app-container container-xxl">
            <!--begin::Category-->
            <div class="card card-flush">
                <!--begin::Card header-->
                <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                    <!--begin::Card title-->
                    <div class="card-title">
                        <!--begin::Search-->
                        <div class="d-flex align-items-center position-relative my-1">
                            <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                            {{-- <span class="svg-icon svg-icon-1 position-absolute ms-4">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2"
                                        rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
                                    <path
                                        d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z"
                                        fill="currentColor"></path>
                                </svg> --}}
                            </span>
                            <!--end::Svg Icon-->
                            {{-- <input type="text" data-kt-ecommerce-category-filter="search"
                                class="form-control form-control-solid w-250px ps-14" placeholder="Cari Category"> --}}
                        </div>
                        <!--end::Search-->
                    </div>
                    <!--end::Card title-->
                    <!--begin::Card toolbar-->
                    <div class="card-toolbar">
                        <!--begin::Add customer-->
                        <a href="/dashbord/background/create" class="btn btn-success">Tambah Background  <i class="bi bi-plus-lg"></i></a>
                        <!--end::Add customer-->
                    </div>
                    <!--end::Card toolbar-->
                </div>
                <!--end::Card header-->
                <!--begin::Card body-->
                <div class="card-body pt-0">
                    <!--begin::Table-->
                    <div class="table-responsive">
                        <table class="table table-hover table-rounded table-striped border gy-7 gs-7">
                            <thead>
                                <tr class="fw-semibold fs-6 text-gray-800 border-bottom-2 border-gray-200">
                                    <th class="text-center">Gambar</th>
                                  
                               
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($background as $background)
                                    <tr>
                                        <td class="text-center">
                                            <img src="{{ asset('storage/' .  $background->gambar ) }}" alt="gambar" class="img-fluid" width="100">
                                        </td>
                                        <td>
                                        <td class="text-end">
                                            <form action="{{ route('background.destroy', $background->id) }}" method="post" class="d-inline">
                                                @method('delete')
                                                @csrf
                                            <button type="submit" class="btn btn-danger border-0 btn-sm mb-2 me-2 mt-10" onclick="return confirm('apakah anda yakin menghapus data ini ?')">Hapus</button>
                                            </form>

                                        <a href="{{ url('dashbord/background/' .$background->id. '/edit') }}" class="btn btn-primary btn-sm mb-2 me-2 mt-10">Edit</a>
                                        </td>
                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                {{-- <div class="row">
                    <div
                        class="col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start">
                        <div class="dataTables_length" id="kt_ecommerce_category_table_length"><label><select
                                    name="kt_ecommerce_category_table_length" aria-controls="kt_ecommerce_category_table"
                                    class="form-select form-select-sm form-select-solid">
                                    <option value="10">10</option>
                                    <option value="25">25</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                </select></label></div>
                    </div>
                    <div class="col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end">
                        <div class="dataTables_paginate paging_simple_numbers" id="kt_ecommerce_category_table_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item previous disabled"
                                    id="kt_ecommerce_category_table_previous"><a href="#"
                                        aria-controls="kt_ecommerce_category_table" data-dt-idx="0" tabindex="0"
                                        class="page-link"><i class="previous"></i></a></li>
                                <li class="paginate_button page-item active"><a href="#"
                                        aria-controls="kt_ecommerce_category_table" data-dt-idx="1" tabindex="0"
                                        class="page-link">1</a></li>
                                <li class="paginate_button page-item "><a href="#"
                                        aria-controls="kt_ecommerce_category_table" data-dt-idx="2" tabindex="0"
                                        class="page-link">2</a></li>
                                <li class="paginate_button page-item next" id="kt_ecommerce_category_table_next"><a
                                        href="#" aria-controls="kt_ecommerce_category_table" data-dt-idx="3"
                                        tabindex="0" class="page-link"><i class="next"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div> --}}
            </div>
            <!--end::Table-->
        </div>
        <!--end::Card body-->
    </div>
    <!--end::Category-->
    </div>
    <!--end::Content container-->
    </div>
@endsection