routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\RatingController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\KatalogController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashbordController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\kategoriController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\KeranjangController;
use App\Http\Controllers\BackgroundController;
use App\Http\Controllers\KonfirmasiController;
use App\Http\Controllers\PengirimanController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\SpesifikasiProdukController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);
Route::get('/detail/{id}', [BlogController::class, 'index']);
Route::get('/kategori/{id}', [CatalogController::class, 'index']);


Route::post('/konfirmasi', [CheckoutController::class, 'konfirmasi'])->middleware('auth');

Route::post('/pembayaran', [PengirimanController::class, 'pembayaran'])->middleware('auth');
Route::get('/pembayaran/{id}', [PengirimanController::class, 'detailPembayaran'])->middleware('auth');
Route::post('/pembayaranrating/{id}', [RatingController::class, 'ratingPembayaran'])->middleware('auth');

Route::get('/pesanan', [PengirimanController::class, 'pesananSelesai'])->middleware('auth');

Route::post('/pembayaran/{id}/uplod-bukti', [PengirimanController::class, 'update'])->middleware('auth');
Route::get('/checkout', [CheckoutController::class, 'index'])->middleware('auth');
Route::get('/kota/{provinsi_id}', [KotaController::class, 'get']);
Route::post('/checkout/get-ongkir', [CheckoutController::class, 'getOngkir']);
Route::post('/user/selesai/{id}/updatestatusselesai', [PengirimanController::class, 'updatestatususer']);



//menu profile
Route::get('/profile', [ProfileController::class, 'index'])->middleware('auth');
Route::post('/profile/profilesaya', [ProfileController::class, 'profilesaya'])->middleware('auth');

//menu login
Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::get('/logout', [LoginController::class, 'logout']);


//register
Route::get('/register', [RegisterController::class, 'index'])->name('register')->middleware('guest');
Route::post('/register', [RegisterController::class, 'store']);

//front

Route::resource('/dashbord/index', DashbordController::class);
//Dashbord admin
Route::resource('/dashbord/kategori', KategoriController::class);
Route::resource('/dashbord/produk', ProdukController::class);
Route::resource('/dashbord/spesifikasiproduk', SpesifikasiProdukController::class);
Route::resource('/dashbord/kota', KotaController::class);
Route::resource('/dashbord/provinsi', ProvinsiController::class);
Route::resource('/dashbord/background', BackgroundController::class);   
Route::resource('/dashbord/bank', BankController::class);
Route::resource('/dashbord/size', SizeController::class);



//pesanan dahbord
Route::get('/dashbord/pesananbaru', [PengirimanController::class, 'pesananbaru']);
Route::get('/dashbord/pesananbaru/{id}/detail', [PengirimanController::class, 'detailPesanan']);
Route::post('/dashbord/pesananbaru/{id}/updatestatus', [PengirimanController::class, 'updatestatuspesananbaru']);

//proses pesanan
Route::get('/dashbord/sedangdiproses', [PengirimanController::class, 'sedangdiproses']);
Route::get('/dashbord/sedangdiproses/{id}/detail', [PengirimanController::class, 'detailProses']);
Route::post('/dashbord/sedangdiproses/{id}/updatestatus', [PengirimanController::class, 'updatestatussedangdiproses']);

//pengiriman pesanan
Route::get('/dashbord/dalampengiriman', [PengirimanController::class, 'dalampengiriman']);
Route::get('/dashbord/dalampengiriman/{id}/detail', [PengirimanController::class, 'detailPengiriman']);
Route::post('/dashbord/dalampengiriman/{id}/updatestatus', [PengirimanController::class, 'updatestatusdalampengiriman']);
 
//pesanan selesai
Route::get('/dashbord/telahselesai', [PengirimanController::class, 'telahselesai']);
Route::get('/dashbord/telahselesai/{id}/detail', [PengirimanController::class, 'detailSelesai']);

//PDF
Route::get('/dashbord/telahselesai/detail-pdf/{id}', [PdfController::class, 'pdfselesai']);
Route::get('/dashbord/pdfreport/detail-pdf', [PdfController::class, 'reportpdf']);
Route::get('/dashbord/pesananbaru/detail-pdf/{id}', [PdfController::class, 'pdfpesananBaru']);
Route::get('/dashbord/dalampengiriman/detail-pdf/{id}', [PdfController::class, 'pdfdalamPengiriman']);
Route::get('/dashbord/sedangdiproses/detail-pdf/{id}', [PdfController::class, 'pdfsedangDiproses']);

//keranjang
Route::get('/keranjang', [KeranjangController::class, 'index'])->middleware('auth');
Route::post('/keranjang/create', [KeranjangController::class, 'store'])->name('keranjang.store')->middleware('auth');
Route::post('/keranjang/{id}', [KeranjangController::class, 'update'])->middleware('auth');
Route::delete('/keranjang/{id}', [KeranjangController::class, 'delete'])->middleware('auth');

app/Models/Bank.php
<?php

namespace App\Models;
use App\Traits\Uuid;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    use HasFactory;

    protected $fillable = ['uuid','gambar','nm_bank', 'no_rekening', 'atas_nama'];

}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;
use App\Models\Bank;
use Illuminate\Http\Request;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $bank = Bank::all();
        $keyword = $request->keyword;
        $bank = Bank::where(function ($q) use ($keyword) {
            $q->where('nm_bank', 'LIKE', '%' . $keyword . '%');
            $q->orWhere('atas_nama', 'LIKE', '%' . $keyword . '%');
            $q->orWhere('no_rekening', 'LIKE', '%' . $keyword . '%');

        })->paginate(100);
        return view('dashbord.bank.index', compact( 
            'bank',
            'keyword'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tambah = Bank::all();
        return view('dashbord.bank.create', compact(
            'tambah'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nm_bank' => 'required|string',
            'no_rekening' => 'required|string',
            'atas_nama' => 'required|string',
            'gambar' => 'required|file|max:1024'
        ]);
        $bank = $request->all();
        if($request->file('gambar')){
            $bank['gambar'] = $request->file('gambar')->store('Bank-image', 'public');
        }
        Bank::create($bank);
        return redirect('dashbord/bank')->with('successcreate', 'Create Successfull!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function show(Bank $bank)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function edit(Bank $bank)
    {
        return view('dashbord.bank.edit', compact(
            'bank',
            
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bank $bank)
    {
        $validatedData = $request->validate([
            'nm_bank' => 'required|string',
            'no_rekening' => 'required|string',
            'atas_nama' => 'required|string',
            'gambar' => 'required|file|max:1024'
        ]); 
        if($request->file('gambar')){
            $validatedData['gambar'] = $request->file('gambar')->store('Bank-image', 'public');
        }
        $bank = Bank::find($bank->id);
        $bank->update($validatedData);
        return redirect ('dashbord/bank')->with('successupdate', 'Update Successfull!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bank $bank)
    {
        $bank->delete();
        return redirect('dashbord/bank')->with('successdelete', 'Delete Successfull!');
    }
   
}

app/Http/Controllers/DashbordController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Produk;
use App\Models\Rating;
use App\Models\pesanan;
use App\Models\Setting;
use App\Models\Checkout;
use App\Models\Pembayaran;
use App\Models\Pengiriman;
use Illuminate\Http\Request;

class DashbordController extends Controller
{
    public function index()
    {
        $user = User::where('is_admin','0')->paginate(5);
        $produk = Produk::get();
        $totalPendapatan = Checkout::where('status', 'Telah Selesai')->sum('total_harga');
        $totalOngkir = Pengiriman::whereHas('checkout', function ($q) {
            $q->where('status', 'Telah Selesai');
        })->sum('harga_ongkir');
        $totalPendapatan = $totalPendapatan - $totalOngkir;

        $totalPenjualan = pesanan::sum('kuantitas');
        $checkout = Checkout::get();
        $ratingKomen = Rating::where('produk_id')->get();


        return view('dashbord.index', compact(
            'produk',
            'totalPendapatan',
            'totalOngkir',
            'user',
            'checkout',
            'ratingKomen'
        ));
    }
}

resources/views/dashbord/bank/create.blade.php
@extends('dashbord.layouts.main')

@section('container')
<div class="container">
    <div class="card card-custom card-create">
        <div class="card-body">
            <form action="{{ route('bank.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                 <div class="row">
                    <div class="col-md-6">
                        <div class="mb-4">
                            <label class="required form-label">Nama Bank :</label> 
                            <input type="text" placeholder="Nama Bank" name="nm_bank" autocomplete="off" required="required" @error('nm_bank')is-invalid @enderror class="form-control">
                            @error('nm_bank')
                            <div class="invalid-feedback d-block">
                              {{ $message }}
                            </div>
                          @enderror
                        </div>
                    </div> 
                     
                    <div class="col-md-6">
                        <div class="mb-4">
                            <label class="required form-label">No Rekening :</label> 
                            <input type="text" placeholder="No Rekening" autocomplete="off" name="no_rekening" required="required" @error('no_rekening')is-invalid @enderror class="form-control">
                            @error('no_rekening')
                            <div class="invalid-feedback d-block">
                              {{ $message }}
                            </div>
                          @enderror
                        </div>
                    </div> 
                    <div class="col-md-6">
                      <div class="mb-4">
                          <label class="required form-label">Atas Nama :</label> 
                          <input type="text" placeholder="Atas Nama" name="atas_nama" required="required" @error('atas_nama')is-invalid @enderror class="form-control">
                          @error('atas_nama')
                          <div class="invalid-feedback d-block">
                            {{ $message }}
                          </div>
                        @enderror
                      </div>
                  </div>
                      <div class="col-md-6 mb-3">
                        <label class="required form-label">Image</label> 
                        <input type="file" accept="jpg, png, jpeg" name="gambar" class="form-control">
                      </div>
                       <div class="kt-form__actions mt-5">
                         <button type="submit" class="btn btn-primary btn-sm mb-2 me-2">
                           <i class="las la-save fs-2 me-2"></i> SAVE</button> 
                         <a href="/dashbord/bank/"  type="button" class="btn btn-danger btn-sm mb-2 me-2">
                           <i class="las la-ban fs-2 me-2"> </i> CANCEL
                         </a>
                   </div>
             </form>
       </div>
    </div>
</div>

@endsection

resources/views/dashbord/bank/edit.blade.php
@extends('dashbord.layouts.main')


@section('container')
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <div class="toolbar" id="kt_toolbar">
            <div id="kt_toolbar_container" class="container-fluid d-flex flex-stack">
                <div data-kt-swapper="true" data-kt-swapper-mode="prepend"
                    data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}"
                    class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
                    <h1 class="d-flex align-items-center text-dark fw-bolder fs-3 my-1">Bank</h1>
                    <span class="h-20px border-gray-300 border-start mx-4"></span>
                </div>

                <div class="d-flex align-items-center gap-2 gap-lg-3">


                </div>

            </div>

        </div>
        <div class="card card-custom card-create">
            <div class="card-body">
                <form action="{{ url('dashbord/bank/' . $bank->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="_method" value="PATCH">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-4">
                                <label class="required form-label">Nama Bank :</label>
                                <input type="text" placeholder="Nama Bank" name="nm_bank" 
                                    class="form-control" value="{{ $bank->nm_bank }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-4">
                                <label class="required form-label">No Rekening :</label>
                                <input type="text" placeholder="No Rekening" name="no_rekening" 
                                    class="form-control" value="{{ $bank->no_rekening }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-4">
                                <label class="required form-label">Atas Nama :</label>
                                <input type="text" placeholder="Atas Nama" name="atas_nama" 
                                    class="form-control" value="{{ $bank->atas_nama }}">
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="mb-4">
                                <label class="required form-label">Gambar</label>
                                <input type="file" accept="jpg, png, jpeg" name="gambar"  class="form-control" value="{{ $bank->gambar }}">
                            </div>
                        </div>
                        <div class="kt-form__actions mt-5">
                            <button type="submit" class="btn btn-primary btn-sm mb-2 me-2">
                                <i class="las la-save fs-2 me-2"></i> SAVE</button>
                            <a href="/dashbord/bank" type="button" class="btn btn-danger btn-sm mb-2 me-2">
                                <i class="las la-ban fs-2 me-2"> </i> CANCEL
                            </a>
                        </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/dashbord/bank/index.blade.php
@extends('dashbord.layouts.main')

@section('container')
    <div id="kt_app_content" class="app-content flex-column-fluid">
        <!--begin::Content container-->
        <div id="kt_app_content_container" class="app-container container-xxl">
            <!--begin::Category-->
            <div class="card card-flush">
                <!--begin::Card header-->
                <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                    <!--begin::Card title-->
                    <div class="card-title">
                    <form action="{{ url('dashbord/bank') }}" method="GET">

                        <!--begin::Search-->
                        <div class="d-flex align-items-center position-relative my-1">
                            <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                            <span class="svg-icon svg-icon-1 position-absolute ms-4">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2"
                                        rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
                                    <path
                                        d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z"
                                        fill="currentColor"></path>
                                </svg>
                            </span>
                            <!--end::Svg Icon-->
                            <input type="text" name="keyword" data-kt-ecommerce-category-filter="search"
                            class="form-control form-control-solid w-250px ps-14" placeholder="Cari Bank" 
                            value="{{ $keyword }}" autocomplete="off">
                        </div>
                    </form>
                        <!--end::Search-->
                    </div>
                    <!--end::Card title-->
                    <!--begin::Card toolbar-->
                    <div class="card-toolbar">
                        <!--begin::Add customer-->
                        <a href="/dashbord/bank/create" class="btn btn-success">Tambah Bank  <i class="bi bi-plus-lg"></i></a>
                        <!--end::Add customer-->
                    </div>
                    <!--end::Card toolbar-->
                </div>
                <!--end::Card header-->
                <!--begin::Card body-->
                <div class="card-body pt-0">
                    <!--begin::Table-->
                    <div class="table-responsive">
                        <table class="table table-hover table-rounded table-striped border gy-7 gs-7">
                            <thead>
                                <tr class="fw-semibold fs-6 text-gray-800 border-bottom-2 border-gray-200">
                                    <th>Nama bank</th>
                                    <th>No Rekening</th>
                                    <th>Atas Nama</th>
                                    <th class="text-center">Logo</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($bank as $bank)
                                    <tr>
                                        <td>{{ $bank->nm_bank }}</td>
                                        <td>{{ $bank->no_rekening }}</td>
                                        <td>{{ $bank->atas_nama }}</td>
                                        <td class="text-center">
                                            <img src="{{ asset('storage/' .  $bank->gambar ) }}" alt="gambar" class="img-fluid" width="100">
                                        </td>
                                        <td>
                                        <td class="text-end">
                                            <form action="{{ route('bank.destroy', $bank->id) }}" method="post" class="d-inline">
                                                @method('delete')
                                                @csrf
                                            <button type="submit" class="btn btn-danger border-0 btn-sm mb-2 me-2 mt-10" onclick="return confirm('apakah anda yakin menghapus data ini ?')">Hapus</button>
                                            </form>

                                        <a href="{{ url('dashbord/bank/' .$bank->id. '/edit') }}" class="btn btn-primary btn-sm mb-2 me-2 mt-10">Edit</a>
                                        </td>
                                        </td>
                                        
                                        
                                        
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
               
            </div>
            <!--end::Table-->
        </div>
        <!--end::Card body-->
    </div>
    <!--end::Category-->
    </div>
    <!--end::Content container-->
    </div>
@endsection